#
# Docker-compose file for running 6.812/6.825 labs
#
# Notes: 
#    The READMEs are put in ./workspace
#    The workspace will be owned by $USER_UID:$USER_GID
#

# Run as follows:
#
#    1) Cd to the directory containing this file
#    2) Change USER_UID and USER_GID to the desired owner of your files (echo $UID in Docker Quick Start Terminal)
#    3) Run the following command:
#
#        % docker-compose up
#
#    4) Look at output and use the 127.0.0.1 URL (unless you changed the port below)
#

version: '3'

services:
  labs:
    hostname: labs
    image: mitdlh/timeloop-accelergy-pytorch:latest
    ports:
      - "8888:8888"
    volumes:
      - ./workspace:/home/workspace
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - JUPYTER_SWITCHES=--NotebookApp.token=''
